---
- hosts: master
  become: yes
  tasks:
    - name: Initialize the Kubernetes master
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: init_output

    - name: Create .kube directory
      file:
        path: /root/.kube
        state: directory
        mode: '0700'

    - name: Copy Kube admin config
      command: cp /etc/kubernetes/admin.conf /root/.kube/config

    - name: Install Flannel network plugin
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command
      delegate_to: localhost
